FORMAT: 1A
HOST: http://api.spiderlog.net

# Spider Log API
Provides service for Spider Log app family, recording world's spider sightings.

# Group Spiders
Access to Spyder resources

## My Spiders [/spiders]
### Get all my spider sightings [GET]
+ Request
    + Headers
    
            Authorization: Basic ABCDEF
        
+ Response 200 (application/json)

        [
            {
                "signedAt" : "2014-08-29T07:00"
                "imageUrl" : "uid-19247681/201408/1456881209_046a7f4d3d_z.jpeg"
                "description" : "Spyder I saw on train"
                "tags" : [
                    "stripy"
                ]
            },
            {
                "signedAt" : "2014-08-29T13:00"
                "imageUrl" : "uid-19247681/201408/14587204878_91405ee2e1_z.jpeg"
                "description" : "Spyder I saw at office"
                "tags" : [
                    "big"
                ]
            },
            {
                "signedAt" : "2014-08-29T19:00"
                "imageUrl" : "uid-19247681/201408/14776091214_4699046e5d_z.jpeg"
                "description" : "Spyder I saw at office"
                "tags" : [
                    "big",
                    "stripy"
                ]
            }
            
        ]

## My Spiders [/spiders{?page,size}]        
### Get page with my spider sightings [GET]
+ Parameters
    + page:1 (number, required) - page number
    + size:10 (number, required) - page size

+ Request
    + Headers
    
            Authorization: Basic ABCDEF
            x-api-version: 1.0
        
+ Response 200 (application/json)

        {
            "pages":
            {
                "number": 1,
                "size": 10,
                "totalPages": 20
            },
            "spaiers":
            [
                {
                    "signedAt" : "2014-08-29T07:00"
                    "imageUrl" : "uid-19247681/201408/1456881209_046a7f4d3d_z.jpeg"
                    "description" : "Spyder I saw on train"
                    "tags" : [
                        "stripy"
                    ]
                },
                {
                    "signedAt" : "2014-08-29T13:00"
                    "imageUrl" : "uid-19247681/201408/14587204878_91405ee2e1_z.jpeg"
                    "description" : "Spyder I saw at office"
                    "tags" : [
                        "big"
                    ]
                },
                {
                    "signedAt" : "2014-08-29T19:00"
                    "imageUrl" : "uid-19247681/201408/14776091214_4699046e5d_z.jpeg"
                    "description" : "Spyder I saw at office"
                    "tags" : [
                        "big",
                        "stripy"
                    ]
                }
            
            ]        
        }